import os
import json
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

def save_json_report(data, filename):
    """Save JSON report to /reports"""
    filepath = os.path.join(REPORTS_DIR, filename)
    with open(filepath, "w") as f:
        json.dump(data, f, indent=4)
    return filepath

def generate_pdf_report(report_data, filename="report.pdf"):
    """Generate a detailed PDF report from dict data"""
    filepath = os.path.join(REPORTS_DIR, filename)
    c = canvas.Canvas(filepath, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 50, "Cybersecurity Attack & Defense Report")

    # Metadata
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 80, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Section: Attack Summary
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 120, "Attack Summary:")
    c.setFont("Helvetica", 11)
    text = c.beginText(60, height - 140)
    for line in report_data.get("attack_summary", []):
        text.textLine(line)
    c.drawText(text)

    # Section: Defense Summary
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 220, "Defense Summary:")
    c.setFont("Helvetica", 11)
    text = c.beginText(60, height - 240)
    for line in report_data.get("defense_summary", []):
        text.textLine(line)
    c.drawText(text)

    # Section: AI Insights
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 320, "AI Insights & Recommendations:")
    c.setFont("Helvetica", 11)
    text = c.beginText(60, height - 340)
    for line in report_data.get("ai_suggestions", []):
        text.textLine(line)
    c.drawText(text)

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(50, 30, "Generated by Hackathon SOC Dashboard")

    c.save()
    return filepath
